language: node_js
node_js:
  - 13

# Define used services
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t user-udagram-lucasbrogni .
  - docker tag user-udagram-lucasbrogni lucasbrogni/user-udagram-lucasbrogni
  - docker login -u "lucasbrogni" -p "$DOCKER_PASSWORD"
  - docker push lucasbrogni/user-udagram-lucasbrogni
